#exception handeling

try:
    a=2
    b=3
    Exception ZeroDevitionError:
    print('there is an error')
finally:
    print('continue with the following code')